/**
 * Static definitions for every Google Sheet collection
 * surfaced in the DataManager page.
 */

import type { Collection } from './data-manager-types';

export const COLLECTIONS: Collection[] = [
  {
    id: 'fletes',
    icon: '🚛',
    label: 'Fletes',
    tab: 'Reporte_Fletes_Transporte',
    emptyMessage: 'Aún no hay fletes registrados',
    columns: [
      { label: 'Fecha',     index: 0, sticky: true, minWidth: '110px' },
      { label: 'Hora',      index: 1, mono: true, hideOnMobile: true, minWidth: '70px' },
      { label: 'Unidad',    index: 2, mono: true, minWidth: '90px' },
      { label: 'Conductor', index: 3, minWidth: '140px' },
      { label: 'KM Carg',   index: 4, align: 'right', mono: true, hideOnMobile: true },
      { label: 'KM Vac',    index: 5, align: 'right', mono: true, hideOnMobile: true },
      { label: 'Origen',    index: 6, hideOnMobile: true, minWidth: '130px' },
      { label: 'Destino',   index: 7, minWidth: '130px' },
      { label: 'KM Total',  index: 8, align: 'right', mono: true },
      { label: 'Cliente',   index: 9, hideOnMobile: true, minWidth: '140px' },
      { label: 'Material',  index: 10, hideOnMobile: true, minWidth: '130px' },
      { label: 'Tonelaje',  index: 11, align: 'right', mono: true },
      { label: 'Flete',     index: 12, align: 'right', mono: true, currency: true },
    ],
  },
  {
    id: 'combustible',
    icon: '⛽',
    label: 'Combustible',
    tab: 'Combustible',
    emptyMessage: 'Aún no hay cargas de combustible registradas',
    // Sheet cols: #(0) FECHA(1) HORA(2) UNIDAD(3) OPERADOR(4) TIPO(5) LITROS(6)
    //             COSTO(7) HOROMETRO(8) KM(9) RENDIMIENTO(10) ESTACION(11) OBSERVACIONES(12)
    columns: [
      { label: 'Fecha',         index: 1, sticky: true, minWidth: '110px' },
      { label: 'Hora',          index: 2, mono: true, hideOnMobile: true, minWidth: '70px' },
      { label: 'Unidad',        index: 3, mono: true, minWidth: '90px' },
      { label: 'Operador',      index: 4, minWidth: '140px' },
      { label: 'Tipo Comb',     index: 5, hideOnMobile: true },
      { label: 'Litros',        index: 6, align: 'right', mono: true },
      { label: 'Costo',         index: 7, align: 'right', mono: true, currency: true },
      { label: 'Horóm',         index: 8, align: 'right', mono: true, hideOnMobile: true },
      { label: 'KM',            index: 9, align: 'right', mono: true, hideOnMobile: true },
      { label: 'Rendimiento',   index: 10, align: 'right', mono: true, hideOnMobile: true },
      { label: 'Estación',      index: 11, hideOnMobile: true, minWidth: '130px' },
      { label: 'Observaciones', index: 12, hideOnMobile: true, minWidth: '160px' },
    ],
  },
  {
    id: 'gastos',
    icon: '💰',
    label: 'Gastos',
    tab: '02 Gastos',
    emptyMessage: 'Aún no hay gastos registrados',
    columns: [
      { label: 'Fecha',       index: 0, sticky: true, minWidth: '110px' },
      { label: 'ID Gasto',    index: 1, mono: true, hideOnMobile: true },
      { label: 'Fecha Doc',   index: 2, hideOnMobile: true, minWidth: '110px' },
      { label: 'Tipo',        index: 3 },
      { label: 'Proveedor',   index: 4, minWidth: '160px' },
      { label: 'RFC',         index: 5, mono: true, hideOnMobile: true },
      { label: 'Folio',       index: 6, mono: true, hideOnMobile: true },
      { label: 'Subtotal',    index: 7, align: 'right', mono: true, currency: true, hideOnMobile: true },
      { label: 'IVA',         index: 8, align: 'right', mono: true, currency: true, hideOnMobile: true },
      { label: 'Total',       index: 9, align: 'right', mono: true, currency: true },
      { label: 'Unidad',      index: 10, mono: true },
      { label: 'OT Ref',      index: 11, mono: true, hideOnMobile: true },
      { label: 'Solicitante', index: 12, hideOnMobile: true },
      { label: 'Método',      index: 13, hideOnMobile: true },
      { label: 'Status',      index: 14, badge: 'status' },
    ],
  },
  {
    id: 'averias',
    icon: '⚠️',
    label: 'Averías',
    tab: 'Averías',
    emptyMessage: 'No hay averías reportadas',
    columns: [
      { label: 'Fecha',       index: 0, sticky: true, minWidth: '110px' },
      { label: 'ID',          index: 1, mono: true, hideOnMobile: true },
      { label: 'Unidad',      index: 2, mono: true, minWidth: '90px' },
      { label: 'Tipo',        index: 3, hideOnMobile: true },
      { label: 'Descripción', index: 4, minWidth: '200px' },
      { label: 'Severidad',   index: 5, badge: 'severity' },
      { label: 'Técnico',     index: 6, hideOnMobile: true },
      { label: 'Status',      index: 7, badge: 'status' },
    ],
  },
  {
    id: 'ot',
    icon: '🔧',
    label: 'Órdenes de Trabajo',
    tab: 'ORDENES_TRABAJO',
    emptyMessage: 'No hay órdenes de trabajo',
    columns: [
      { label: 'Fecha',       index: 0, sticky: true, minWidth: '110px' },
      { label: 'OT ID',       index: 1, mono: true },
      { label: 'Fecha Doc',   index: 2, hideOnMobile: true, minWidth: '110px' },
      { label: 'Unidad',      index: 3, mono: true, minWidth: '90px' },
      { label: 'Tipo',        index: 4, hideOnMobile: true },
      { label: 'Descripción', index: 5, minWidth: '200px' },
      { label: 'Severidad',   index: 6, badge: 'severity' },
      { label: 'Técnico',     index: 7, hideOnMobile: true },
      { label: 'Status',      index: 8, badge: 'status' },
    ],
  },
  {
    id: 'horometros',
    icon: '⏱️',
    label: 'Horómetros',
    tab: '04B Registro Horómetros',
    emptyMessage: 'Aún no hay lecturas de horómetro',
    columns: [
      { label: 'Fecha',     index: 0, sticky: true, minWidth: '110px' },
      { label: 'Hora',      index: 1, mono: true, hideOnMobile: true },
      { label: 'Unidad',    index: 2, mono: true, minWidth: '90px' },
      { label: 'Modelo',    index: 3, hideOnMobile: true, minWidth: '130px' },
      { label: 'Operador',  index: 4, minWidth: '140px' },
      { label: 'Turno',     index: 5, hideOnMobile: true },
      { label: 'Horómetro', index: 6, align: 'right', mono: true },
      { label: 'Próx PM',   index: 7, align: 'right', mono: true, hideOnMobile: true },
      { label: 'Faltan',    index: 8, align: 'right', mono: true },
    ],
  },
  {
    id: 'viajes_pena',
    icon: '🏔️',
    label: 'Viajes Peña',
    tab: 'Reporte_Viajes_Peña',
    emptyMessage: 'Aún no hay viajes a Peña registrados',
    // Sheet cols: #(0) FECHA(1) HORA(2) CAMION(3) CONDUCTOR(4) RUTA ORIGEN(5)
    //             RUTA DESTINO(6) KM CARGADO(7) KM VACIO(8) KM TOTAL(9)
    //             MATERIAL(10) TONELAJE(11) OBSERVACIONES(12)
    columns: [
      { label: 'Fecha',         index: 1, sticky: true, minWidth: '110px' },
      { label: 'Hora',          index: 2, mono: true, hideOnMobile: true },
      { label: 'Unidad',        index: 3, mono: true, minWidth: '90px' },
      { label: 'Conductor',     index: 4, minWidth: '140px' },
      { label: 'Origen',        index: 5, hideOnMobile: true, minWidth: '130px' },
      { label: 'Destino',       index: 6, minWidth: '130px' },
      { label: 'KM Carg',       index: 7, align: 'right', mono: true, hideOnMobile: true },
      { label: 'KM Vac',        index: 8, align: 'right', mono: true, hideOnMobile: true },
      { label: 'KM Total',      index: 9, align: 'right', mono: true },
      { label: 'Material',      index: 10, hideOnMobile: true },
      { label: 'Tonelaje',      index: 11, align: 'right', mono: true },
      { label: 'Observaciones', index: 12, hideOnMobile: true, minWidth: '200px' },
    ],
  },
  {
    id: 'inspecciones',
    icon: '📋',
    label: 'Inspecciones',
    tab: '14 Inspecciones',
    emptyMessage: 'Aún no hay inspecciones registradas',
    // Sheet cols: #(0) INSP_ID(1) FECHA(2) HORA(3) CODIGO UNIDAD(4) MODELO(5)
    //             OPERADOR(6) TIPO(7) HOROMETRO(8) ...checks... SCORE(N-3) RESULTADO(N-2)
    columns: [
      { label: 'Fecha',     index: 2, sticky: true, minWidth: '110px' },
      { label: 'Hora',      index: 3, mono: true, hideOnMobile: true },
      { label: 'Folio',     index: 1, mono: true, hideOnMobile: true },
      { label: 'Unidad',    index: 4, mono: true, minWidth: '90px' },
      { label: 'Modelo',    index: 5, hideOnMobile: true, minWidth: '130px' },
      { label: 'Operador',  index: 6, minWidth: '140px' },
      { label: 'Tipo Insp', index: 7, hideOnMobile: true },
      { label: 'Horómetro', index: 8, align: 'right', mono: true, hideOnMobile: true },
    ],
  },
];
